# Generated by Django 5.1.1 on 2024-10-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='EMAIL',
        ),
    ]
